openapi: 3.1.0
info:
  title: Doppler Native Integration Specification
  description: Complete configuration and workflow for Doppler CLI credential management
  version: 1.0.0

components:
  schemas:
    DopplerSetup:
      type: object
      description: Doppler CLI installation and authentication setup
      properties:
        installation:
          type: object
          properties:
            command:
              type: string
              example: "brew install dopplerhq/cli/doppler"
            path:
              type: string
              example: "/opt/homebrew/bin/doppler"
        authentication:
          type: object
          properties:
            login:
              type: string
              example: "doppler login"
            workplace:
              type: string
              example: "eon"
            verification:
              type: string
              example: "doppler me"

    DopplerWorkflow:
      type: object
      description: Standard Doppler operational workflows
      properties:
        discovery:
          type: array
          items:
            type: string
          example:
            - "doppler projects"
            - "doppler configs"
            - "doppler secrets"
        setup:
          type: string
          example: "doppler setup --project <name> --config <env>"
        execution:
          type: string
          example: "doppler run -- <command>"
        verification:
          type: string
          example: "doppler run -- env | grep <SERVICE>"

    DopplerArchitecture:
      type: object
      description: Doppler project hierarchy and policies
      properties:
        hierarchy:
          type: string
          example: "Project → Environment → Config"
        policy:
          type: string
          example: "Single credential per service, Doppler as exclusive source"
        environment_separation:
          type: string
          example: "Production credentials properly isolated"
        deployment_integration:
          type: string
          example: "doppler run -- shuttle deploy"

paths: {}