openapi: 3.1.0
info:
  title: Pushover Integration Specification
  description: Complete configuration for Pushover notification service integration
  version: 1.0.0

components:
  schemas:
    PushoverAPI:
      type: object
      description: Pushover API configuration and endpoints
      properties:
        base_url:
          type: string
          example: "https://pushover.net/api"
        documentation:
          type: string
          example: "https://pushover.net/api"

    PushoverCredentials:
      type: object
      description: Keychain-stored credentials for Pushover service
      properties:
        keychain_items:
          type: object
          properties:
            user_key:
              type: string
              example: "pushover-user-key"
            app_token:
              type: string
              example: "pushover-app-token"
            email:
              type: string
              example: "pushover-email"
        account:
          type: string
          example: "terryli"

    PushoverSounds:
      type: object
      description: Available notification sounds for Pushover
      properties:
        available_sounds:
          type: array
          items:
            type: string
          example:
            - "toy_story"
            - "dune"
            - "bike"
            - "siren"
            - "cosmic"
            - "alien"
            - "vibrate"
            - "none"
        default_sound:
          type: string
          example: "toy_story"

    PushoverIntegration:
      type: object
      description: Complete Pushover integration configuration
      properties:
        api:
          $ref: '#/components/schemas/PushoverAPI'
        credentials:
          $ref: '#/components/schemas/PushoverCredentials'
        sounds:
          $ref: '#/components/schemas/PushoverSounds'

paths: {}