openapi: 3.1.0
info:
  title: PyPI Publishing Methods Specification
  description: Complete configuration for PyPI package publishing workflows
  version: 1.0.0

components:
  schemas:
    LegacyTokenMethod:
      type: object
      description: Token-based PyPI publishing (backup method)
      properties:
        status:
          type: string
          enum: ["backup_only"]
        location:
          type: string
          example: "$HOME/.pypirc"
        platform_restriction:
          type: string
          example: "terryli's macOS MacBook only - not stored elsewhere"
        authentication:
          type: object
          properties:
            username:
              type: string
              example: "__token__"
            manual_command:
              type: string
              example: "uv publish --token \"pypi-[TOKEN]\""
            token_format:
              type: string
              example: "pypi-AgEI..."
            unique_identifier:
              type: string
              example: "cc934ce2-87dc-4995-812b-1149d7e977cf"

    TrustedPublishing:
      type: object
      description: OIDC-based trusted publishing (primary method)
      properties:
        status:
          type: string
          enum: ["primary_method"]
        year_designation:
          type: string
          example: "2025 Best Practice"
        security:
          type: string
          example: "OIDC-based authentication (no stored tokens)"
        automation:
          type: string
          example: "GitHub Actions with .github/workflows/publish.yml"
        environments:
          type: object
          properties:
            production:
              type: string
              example: "pypi"
            testing:
              type: string
              example: "testpypi"
        approval_process:
          type: string
          example: "Manual approval required for production releases"
        features:
          type: array
          items:
            type: string
          example:
            - "Digital attestations"
            - "Sigstore signatures"
            - "Zero-credential workflow"
        documentation:
          type: string
          example: "docs/PUBLISHING.md for complete setup guide"

paths: {}